### ISSUE TITLE
Run the demo.py but cannot display the result.

### ISSUE THREAD

**Issue by SunJJ1996** [VisualComputingInstitute/DR-SPAAM-Detector#2]
thank you for share your project.
i prepared all the repository, and when i run demo.py in Pycharm: 
`if __name__ == "__main__":`
`play_sequence()`
it is not error, but the plot dose not move and generate many empty plots.
i dont know how to submit pic in git, but i also waiting for your reply.
thanks

**Comment by danjia21** [comment]
Hi @SunJJ1996, I just verified that both `python bin/demo.py --dets` and `python bin/demo.py --tracks` works. The error is probably related to plotting in Pycharm. Can you run these commands in a terminal? Alternatively, you can modify demo.py such that it saves the figure, rather than displaying them.

**Comment by SunJJ1996** [comment]
> Hi @SunJJ1996, I just verified that both `python bin/demo.py --dets` and 'python bin/demo.py --tracks` works. The error is probably related to plotting in Pycharm. Can you run these commands in a terminal? Alternatively, you can modify demo.py such that it saves the figure, rather than displaying them.

thank you for your reply. I run this project in a server so the terminal cannot display plot. do you have any suggestion in how to  
 save the displaying result?
thanks

**Comment by danjia21** [comment]
You can save the figure for each frame and transfer them to your local machine. Uncomment this line
https://github.com/VisualComputingInstitute/DR-SPAAM-Detector/blob/master/dr_spaam/bin/demo.py#L122
and comment out the `plt.pause()`

**Comment by danjia21** [comment]
> > Hi @SunJJ1996, I just verified that both `python bin/demo.py --dets` and 'python bin/demo.py --tracks` works. The error is probably related to plotting in Pycharm. Can you run these commands in a terminal? Alternatively, you can modify demo.py such that it saves the figure, rather than displaying them.
> 
> thank you for your reply. I run this project in a server so the terminal cannot display plot. do you have any suggestion in how to
> save the displaying result?
> thanks

You can save the figure for each frame and transfer them to your local machine. Uncomment this line
https://github.com/VisualComputingInstitute/DR-SPAAM-Detector/blob/master/dr_spaam/bin/demo.py#L122
and comment out the plt.pause()

**Comment by SunJJ1996** [comment]
> > > Hi @SunJJ1996, I just verified that both `python bin/demo.py --dets` and 'python bin/demo.py --tracks` works. The error is probably related to plotting in Pycharm. Can you run these commands in a terminal? Alternatively, you can modify demo.py such that it saves the figure, rather than displaying them.
> > 
> > 
> > thank you for your reply. I run this project in a server so the terminal cannot display plot. do you have any suggestion in how to
> > save the displaying result?
> > thanks
> 
> You can save the figure for each frame and transfer them to your local machine. Uncomment this line
> https://github.com/VisualComputingInstitute/DR-SPAAM-Detector/blob/master/dr_spaam/bin/demo.py#L122
> and comment out the plt.pause()

OK, it really helpful. thank you again.
