### ISSUE TITLE
how to trans my .bag file to .bag.csv?

### ISSUE THREAD

**Issue by SunJJ1996** [VisualComputingInstitute/DR-SPAAM-Detector#4]
i want to use this project for my own data, i just have the .bag files generated by laser.
is there some python scripts or something to do this?

**Comment by danjia21** [comment]
Hi @SunJJ1996 I didn't provide a script for it, but you can use rosbag API to write one yourself. 
http://wiki.ros.org/rosbag/Code%20API

Just make sure that the final csv follows the correct DROW format defined here
https://github.com/VisualComputingInstitute/DROW

There is a script to pack DROW sequence into a ROS bag (the reverse of what you want to do).
https://github.com/VisualComputingInstitute/DR-SPAAM-Detector/blob/master/dr_spaam_ros/scripts/drow_data_converter.py

**Comment by SunJJ1996** [comment]
OK, i will try. thanks
