### ISSUE TITLE
FPS Issue

### ISSUE THREAD

**Issue by Alex-Beh** [VisualComputingInstitute/DR-SPAAM-Detector#5]
Hello, thanks for the great contribution. I have tried the model on nvidia xavier NX.

When I try `rostopic hz /dr_spaam_detections`, I get around 0.2Hz instead of 20Hz++ that shown in the documentation. Do you have any ideas on that?

**Comment by danjia21** [comment]
Hi @Alex-Beh , the inference speed would depend on a few things. Here are some general comments

1. The reported inference speed was measured on a Jetson AGX Xavier (it has a stronger GPU than Xavier NX) with max performance.

```
$ sudo nvpmodel -m 0     # on Xavier NX, use -m 2  instead (15W 6-core mode)
$ sudo jetson_clocks
``` 

2. `rostopic hz` depend on how many other process that are running. Try instead using `python bin/demo.py --time` to measure the throughput of the network.

3. How many points are in your scan? More points means the network has to run more forward passes (hence slower). The reported inference time was taken with 450 points. To speed things up, you can set `stride` to a higher value. It should not reduce accuracy.

**Comment by Alex-Beh** [comment]
I tried change the stride from 1 to 2.

It give the following error:
```
[ERROR] [1607569215.892079]: bad callback: <bound method DrSpaamROS._scan_callback of <dr_spaam_ros.dr_spaam_ros.DrSpaamROS object at 0x7f179c2a90>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/catkin_ws/src/DR-SPAAM-Detector/dr_spaam_ros/src/dr_spaam_ros/dr_spaam_ros.py", line 62, in _scan_callback
    dets_xy, dets_cls, _ = self._detector(scan)
  File "/usr/local/lib/python3.6/dist-packages/dr_spaam-1.1-py3.6.egg/dr_spaam/detector.py", line 88, in __call__
    stride=self._stride, **self._ct_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dr_spaam-1.1-py3.6.egg/dr_spaam/utils/utils.py", line 158, in scans_to_cutout
    ang_ct = scan_phi[::stride] - half_alpha + np.arange(num_cutout_pts).reshape(num_cutout_pts, 1, 1) * delta_alpha
ValueError: operands could not be broadcast together with shapes (360,) (1,720) 
```

The weight file that I using is dr_spaam_e40.pth.

**Comment by danjia21** [comment]
I've pushed a bug fix. Can you try if using stride works now?
