### ISSUE TITLE
Error launching ros node

### ISSUE THREAD

**Issue by PedromsLeal** [VisualComputingInstitute/DR-SPAAM-Detector#6]
Hello, I followed the installation steps, the only difference would be that I used python3 here: "python setup.py install" instead of python. 

I compiled the dr_spaam_ros pack and it tried to launch the node however I was met with the following weird error.

`... logging to /home/pedro/.ros/log/af40bed4-9243-11eb-a885-8d8ffcb1084e/roslaunch-pedro-Legion-Y540-15IRH-36436.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://pedro-Legion-Y540-15IRH:41101/

SUMMARY
========

PARAMETERS
 * /dr_spaam_ros/conf_thresh: 0.1
 * /dr_spaam_ros/publisher/detections/latch: False
 * /dr_spaam_ros/publisher/detections/queue_size: 1
 * /dr_spaam_ros/publisher/detections/topic: /dr_spaam_detections
 * /dr_spaam_ros/publisher/rviz/latch: False
 * /dr_spaam_ros/publisher/rviz/queue_size: 1
 * /dr_spaam_ros/publisher/rviz/topic: /dr_spaam_rviz
 * /dr_spaam_ros/stride: 1
 * /dr_spaam_ros/subscriber/scan/queue_size: 1
 * /dr_spaam_ros/subscriber/scan/topic: /sick_laser_front...
 * /dr_spaam_ros/weight_file: /home/dan/git/DR-...
 * /rosdistro: noetic
 * /rosversion: 1.15.9

NODES
  /
    dr_spaam_ros (dr_spaam_ros/node.py)

auto-starting new master
process[master]: started with pid [36444]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to af40bed4-9243-11eb-a885-8d8ffcb1084e
process[rosout-1]: started with pid [36454]
started core service [/rosout]
process[dr_spaam_ros-2]: started with pid [36461]
Traceback (most recent call last):
  File "/home/pedro/DR-SPAAM-Detector/src/dr_spaam_ros/scripts/node.py", line 10, in <module>
    DrSpaamROS()
  File "/home/pedro/DR-SPAAM-Detector/src/dr_spaam_ros/src/dr_spaam_ros/dr_spaam_ros.py", line 16, in __init__
    self._detector = Detector(
  File "/usr/local/lib/python3.8/dist-packages/dr_spaam-1.1-py3.8.egg/dr_spaam/detector.py", line 68, in __init__
  File "/home/pedro/.local/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/pedro/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/pedro/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/dan/git/DR-SPAAM-Detector_private/dr_spaam/ckpts/dr_spaam_e40.pth'
[dr_spaam_ros-2] process has died [pid 36461, exit code 1, cmd /home/pedro/DR-SPAAM-Detector/src/dr_spaam_ros/scripts/node.py __name:=dr_spaam_ros __log:=/home/pedro/.ros/log/af40bed4-9243-11eb-a885-8d8ffcb1084e/dr_spaam_ros-2.log].
log file: /home/pedro/.ros/log/af40bed4-9243-11eb-a885-8d8ffcb1084e/dr_spaam_ros-2*.log`

Where did I mess up for it to be looking into:  '/home/dan/git/DR-SPAAM-Detector_private/dr_spaam/ckpts/dr_spaam_e40.pth'?

**Comment by danjia21** [comment]
You should change the path to your checkpoint file
https://github.com/VisualComputingInstitute/DR-SPAAM-Detector/blob/master/dr_spaam_ros/config/dr_spaam_ros.yaml#L1

**Comment by PedromsLeal** [comment]
@danjia21 

It is now working properly, I assumed that the config files were only to remap the topics and since I wasn't getting to the point where I was needing them to be remapped I didn't look into them!

Thank you for your fast response!
